version: '2'
services:
  aplicativo-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.8
#    volumes:
#      - ./central-server-config/central-config
    ports:
    - 9200:9200
    - 9300:9300

    environment:
      - 'ES_JAVA_OPTS=-Xms1024m'
      - 'discovery.type=single-node'